python train.py \
--name painter_generative_new \
--gpu_ids 0 \
--model painter \
--dataset_mode null \
--batch_size 32 \
--display_freq 25 \
--print_freq 25 \
--lr 1e-4 \
--init_type normal \
--n_epochs 200 \
--n_epochs_decay 20 \
--max_dataset_size 16384 \
--save_epoch_freq 20 \
--display_port 8090 \
--generative
